version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ilcs
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: db_ilcs
      MYSQL_USER: denaaay
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  backend:
    build:
      context: ./backend
    container_name: backend_ilcs
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend_ilcs
    image: node:23
    depends_on:
      - mysql
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  mysql-data:
  node_modules: