version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ilcs
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: db_ilcs
      MYSQL_USER: denaaay
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: