version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ilcs
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: db_ilcs
      MYSQL_USER: denaaay
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  backend:
    build:
      context: ./backend
    image: node:23
    container_name: backend_ilcs
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app

volumes:
  mysql-data: